export enum Languages {
  HTML = 'HTML',
  JavaScript = 'JavaScript',
  CSS = "CSS",
  SCSS = 'SCSS',
  TypeScript = 'TypeScript',
  React = 'React',
  StyledComponents = 'Styled Components',
  ReactNative = 'React Native',
  Redux = 'Redux',
  ReduxSaga = 'Redux Saga',
  ReduxToolkit = 'Redux (toolkit)',
  ReactNativeTestingLibrary = 'React Native Testing Library',
  Apisauce = 'apisauce',
  Jest = "jest",
  NextJs = 'Next.js',
  Webpack = 'Webpack',
  AntDesign = 'Ant Design',
  Leaflet = 'Leaflet',

}